package PlantUMLTarget.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new AltFragment_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new LoopFragment_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new MessageLine_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new PUMLFile_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x3946306a58ce49edL, 0x90e5f6877939cd31L, 0x3cf5cbefbb5c29e1L), MetaIdFactory.conceptId(0x3946306a58ce49edL, 0x90e5f6877939cd31L, 0x543e8aec4e3d4879L), MetaIdFactory.conceptId(0x3946306a58ce49edL, 0x90e5f6877939cd31L, 0x543e8aec4e2006c5L), MetaIdFactory.conceptId(0x3946306a58ce49edL, 0x90e5f6877939cd31L, 0x543e8aec4e2006bcL)).seal();
}
