package ImporterPluginSolution.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.applicationplugins.BaseApplicationPlugin;
import com.intellij.openapi.extensions.PluginId;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.ide.actions.ProjectPanePopupMenu_ActionGroup;

public class ImporterPluginSolution_ApplicationPlugin extends BaseApplicationPlugin {
  private final PluginId myId = PluginId.getId("ImporterPluginSolution");

  public ImporterPluginSolution_ApplicationPlugin() {
  }

  @NotNull
  public PluginId getId() {
    return myId;
  }

  public void createGroups() {
    // actions w/o parameters
    addAction(new testImportPlugin_Action());
    // groups
    addGroup(new ImportActionGroup_ActionGroup(this));
  }
  public void adjustRegularGroups() {
    insertGroupIntoAnother(ImportActionGroup_ActionGroup.ID, ProjectPanePopupMenu_ActionGroup.ID, null);
  }
}
