package ImporterPluginSolution.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.workbench.action.ApplicationPlugin;

public class ImportActionGroup_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "ImporterPluginSolution.plugin.ImportActionGroup_ActionGroup";

  public ImportActionGroup_ActionGroup(@NotNull ApplicationPlugin plugin) {
    super("ImportActionGroup", ID, plugin);
    setIsInternal(false);
    setPopup(true);
    ImportActionGroup_ActionGroup.this.addAction("ImporterPluginSolution.plugin.testImportPlugin_Action");
  }
}
