package ImporterPluginSolution.plugin;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.Files;
import com.google.gson.Gson;
import com.google.gson.JsonObject;
import java.util.Map;
import java.util.HashMap;
import com.google.gson.JsonArray;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import com.google.gson.JsonElement;
import jetbrains.mps.internal.collections.runtime.Sequence;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class JsonImporter {

  public static void importJSON(SNode ecg) {
    String path = "/Users/alessandramancas/projects/appliJava/ecg.json";
    Path p = Paths.get(path);
    System.out.println("HELLOO");
    try {
      String content = new String(Files.readAllBytes(p));

      Gson gson = new Gson();
      JsonObject JSONRoot = gson.fromJson(content, JsonObject.class);

      Map<String, SNode> methodMap = new HashMap<>();
      JsonArray methods = JSONRoot.getAsJsonArray("methods");

      // create methods only
      for (Integer i = 0; i < methods.size(); i++) {
        JsonObject m = methods.get(i).getAsJsonObject();

        String name = m.get("id").getAsString();
        String methodName = m.get("methodName").getAsString();
        String signatureString = m.get("signature").getAsString();
        String returnType = m.get("returnType").getAsString();
        String className = m.get("className").getAsString();
        String isEntry = m.get("isEntry").getAsString();

        System.out.println("ISENTRY " + isEntry.toString());

        SNode newMethod = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c0072eL, "EnhancedCallGraph.structure.Method"));
        SPropertyOperations.assign(newMethod, PROPS.name$MnvL, name);
        SPropertyOperations.assign(newMethod, PROPS.methodName$KVVq, methodName);
        SPropertyOperations.assign(newMethod, PROPS.signature$8N8I, signatureString);
        SPropertyOperations.assign(newMethod, PROPS.className$KVGp, className);
        SPropertyOperations.assign(newMethod, PROPS.returnType$8TWb, returnType);
        if (isEntry.equals("true")) {
          SPropertyOperations.assign(newMethod, PROPS.isEntry$8MEG, true);
        } else if (isEntry.equals("false")) {
          SPropertyOperations.assign(newMethod, PROPS.isEntry$8MEG, false);
        }

        ListSequence.fromList(SLinkOperations.getChildren(ecg, LINKS.methods$l8cE)).addElement(newMethod);
        methodMap.put(signatureString, newMethod);
      }

      System.out.println(methodMap.toString());

      //  set entryMethod
      for (SNode m : SLinkOperations.getChildren(ecg, LINKS.methods$l8cE)) {
        if (SPropertyOperations.getBoolean(m, PROPS.isEntry$8MEG)) {
          SLinkOperations.setTarget(ecg, LINKS.entryMethod$61f3, m);
        }
      }

      //  add the cfg & params 
      for (Integer i = 0; i < methods.size(); i++) {

        JsonObject m = methods.get(i).getAsJsonObject();

        System.out.println("START CFG FOR: " + m.get("id").getAsString());

        SNode modelMethod = null;
        for (SNode mm : ListSequence.fromList(SLinkOperations.getChildren(ecg, LINKS.methods$l8cE))) {
          if (SPropertyOperations.getString(mm, PROPS.name$MnvL).equals(m.get("id").getAsString())) {
            modelMethod = mm;
            System.out.println("Model method " + mm);
          }
        }


        JsonElement paramsElem = m.get("params");
        JsonArray params = new JsonArray();

        if (paramsElem != null && paramsElem.isJsonArray()) {
          params = paramsElem.getAsJsonArray();
        }

        System.out.println("after params");
        JsonObject cfg = m.get("cfg").getAsJsonObject();
        System.out.println("after cfg");

        SNode newCfg = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00733L, "EnhancedCallGraph.structure.ControlFlowGraph"));
        //  leave entryblock blank for now 

        // get all the blocks for this current cfg 
        Map<String, SNode> blockMap = new HashMap<>();

        JsonArray blocks = cfg.get("blocks").getAsJsonArray();
        System.out.println("after blocks");

        JsonElement intElement = cfg.get("interactions");
        JsonArray interactions = null;
        if (intElement != null && intElement.isJsonArray()) {
          interactions = intElement.getAsJsonArray();
        }


        // for each block, create a node<block>
        for (JsonElement b : Sequence.fromIterable(blocks)) {
          JsonObject block = b.getAsJsonObject();
          System.out.println(block.toString());

          SNode newBlock = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00730L, "EnhancedCallGraph.structure.Block"));

          String blockId = block.get("id").getAsString();
          SPropertyOperations.assign(newBlock, PROPS.name$MnvL, blockId);
          SPropertyOperations.assign(newBlock, PROPS.condition$KGVo, block.get("condition").getAsString());

          JsonElement invElem = block.get("invocations");
          if (invElem != null && invElem.isJsonPrimitive() && invElem.getAsString().equals("none")) {
            System.out.println("NONEEEEE");
            ListSequence.fromList(SLinkOperations.getChildren(newCfg, LINKS.blocks$sZ2f)).addElement(newBlock);
            blockMap.put(blockId, newBlock);
            continue;
          }

          // handle invocations
          JsonArray invocations = block.get("invocations").getAsJsonArray();
          System.out.println(invocations);

          for (JsonElement inv : Sequence.fromIterable(invocations)) {
            JsonObject invObject = inv.getAsJsonObject();
            SNode newInv = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0xac4a12cce5dbb29L, "EnhancedCallGraph.structure.Invocation"));
            SPropertyOperations.assign(newInv, PROPS.targetClass$DeM6, invObject.get("targetClass").getAsString());
            String targetSignature = invObject.get("targetSignature").getAsString();
            SPropertyOperations.assign(newInv, PROPS.targetSignature$Dfg8, targetSignature);
            SNode target = methodMap.get(targetSignature);
            if (target != null) {
              SLinkOperations.setTarget(newInv, LINKS.targetMethod$n8Sj, target);
            }
            ListSequence.fromList(SLinkOperations.getChildren(newBlock, LINKS.invocations$KHap)).addElement(newInv);
          }
          System.out.println(newBlock);
          blockMap.put(blockId, newBlock);
          ListSequence.fromList(SLinkOperations.getChildren(newCfg, LINKS.blocks$sZ2f)).addElement(newBlock);
        }

        //  add successors to the blocks (unsure) 
        for (JsonElement b : Sequence.fromIterable(blocks)) {
          JsonObject block = b.getAsJsonObject();
          String id = block.get("id").getAsString();
          SNode modelBlock = blockMap.get(id);

          JsonElement succElem = block.get("successors");
          if (succElem != null && succElem.isJsonPrimitive() && succElem.getAsString().equals("none")) {
            continue;
          }

          JsonArray successors = block.get("successors").getAsJsonArray();
          for (JsonElement s : Sequence.fromIterable(successors)) {
            SNode newRef = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0xac4a12cce81e454L, "EnhancedCallGraph.structure.BlockRef"));
            String succID = s.getAsString();
            SLinkOperations.setTarget(newRef, LINKS.target$ND_8, blockMap.get(succID));
            ListSequence.fromList(SLinkOperations.getChildren(modelBlock, LINKS.successors$7u8o)).addElement(newRef);
          }
        }

        //  add the entryBlock ref
        JsonElement entryBlockElem = cfg.get("entryBlock");
        SNode newEntryBlock = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00730L, "EnhancedCallGraph.structure.Block"));

        if (entryBlockElem != null) {
          String entryID = entryBlockElem.getAsString();
          SLinkOperations.setTarget(newCfg, LINKS.entryBlock$4nNX, blockMap.get(entryID));
          System.out.println("set entry block");
        }

        //  once blocks are added, do interactions
        for (JsonElement inter : Sequence.fromIterable(interactions)) {
          JsonObject interaction = inter.getAsJsonObject();

          String type = interaction.get("type").getAsString();
          String originBlockID = interaction.get("originBlock").getAsString();
          SNode originBlock = blockMap.get(originBlockID);

          if (type.equals("Call")) {
            String targetSignature = interaction.get("targetSignature").getAsString();
            System.out.println("TARGET SIG " + targetSignature);
            SNode newCall = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0xac4a12cce5dbb6fL, "EnhancedCallGraph.structure.MethodCall"));
            SPropertyOperations.assign(newCall, PROPS.type$CSJA, "Call");
            SLinkOperations.setTarget(newCall, LINKS.originBlock$zItN, originBlock);
            SNode tm = methodMap.get(targetSignature);
            System.out.println("TARGETTTtt" + tm);
            SLinkOperations.setTarget(newCall, LINKS.targetMethod$BvBI, methodMap.get(targetSignature));
            ListSequence.fromList(SLinkOperations.getChildren(newCfg, LINKS.interactions$KgkV)).addElement(newCall);
          } else if (type.equals("Loop")) {
            String condition = interaction.get("condition").getAsString();
            JsonArray successors = interaction.get("successors").getAsJsonArray();
            JsonArray backwardJumps = interaction.get("backwardJumps").getAsJsonArray();
            SNode newLoop = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0xac4a12cce5dbb7cL, "EnhancedCallGraph.structure.Loop"));
            SPropertyOperations.assign(newLoop, PROPS.type$CSJA, "Loop");
            SLinkOperations.setTarget(newLoop, LINKS.originBlock$zItN, originBlock);
            SPropertyOperations.assign(newLoop, PROPS.condition$Dej_, condition);
            // build successors array
            for (JsonElement s : Sequence.fromIterable(successors)) {
              SNode newRef = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0xac4a12cce81e454L, "EnhancedCallGraph.structure.BlockRef"));
              String succID = s.getAsString();
              SLinkOperations.setTarget(newRef, LINKS.target$ND_8, blockMap.get(succID));
              ListSequence.fromList(SLinkOperations.getChildren(newLoop, LINKS.successors$CY8X)).addElement(newRef);
            }
            // build backwardjumps array 
            for (JsonElement b : Sequence.fromIterable(backwardJumps)) {
              SNode newRef = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0xac4a12cce81e454L, "EnhancedCallGraph.structure.BlockRef"));
              String id = b.getAsString();
              SLinkOperations.setTarget(newRef, LINKS.target$ND_8, blockMap.get(id));
              ListSequence.fromList(SLinkOperations.getChildren(newLoop, LINKS.backwardJumps$DcVr)).addElement(newRef);
            }
            ListSequence.fromList(SLinkOperations.getChildren(newCfg, LINKS.interactions$KgkV)).addElement(newLoop);
          } else if (type.equals("If")) {
            SNode newIf = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0xac4a12cce5dbb76L, "EnhancedCallGraph.structure.IfStatement"));
            String condition = interaction.get("condition").getAsString();
            SPropertyOperations.assign(newIf, PROPS.type$CSJA, "If");
            SLinkOperations.setTarget(newIf, LINKS.originBlock$zItN, originBlock);
            SPropertyOperations.assign(newIf, PROPS.condition$Dej_, condition);
            ListSequence.fromList(SLinkOperations.getChildren(newCfg, LINKS.interactions$KgkV)).addElement(newIf);
          }
        }

        if (modelMethod != null) {

          SLinkOperations.setTarget(modelMethod, LINKS.cfg$G$Mq, newCfg);
          System.out.println("attaching cfg to: " + modelMethod);
        }

      }


    } catch (Exception e) {
      e.printStackTrace();
    }



  }

  public static void test(SNode ecg) {
    SNode testmethod = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c0072eL, "EnhancedCallGraph.structure.Method"));
    SPropertyOperations.assign(testmethod, PROPS.name$MnvL, "TEST_METHOD");
    ListSequence.fromList(SLinkOperations.getChildren(ecg, LINKS.methods$l8cE)).addElement(testmethod);
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty methodName$KVVq = MetaAdapterFactory.getProperty(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c0072eL, 0xac4a12cce5dbba2L, "methodName");
    /*package*/ static final SProperty signature$8N8I = MetaAdapterFactory.getProperty(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c0072eL, 0x307aac0c73c04429L, "signature");
    /*package*/ static final SProperty className$KVGp = MetaAdapterFactory.getProperty(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c0072eL, 0xac4a12cce5dbba1L, "className");
    /*package*/ static final SProperty returnType$8TWb = MetaAdapterFactory.getProperty(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c0072eL, 0x307aac0c73c04431L, "returnType");
    /*package*/ static final SProperty isEntry$8MEG = MetaAdapterFactory.getProperty(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c0072eL, 0x307aac0c73c04427L, "isEntry");
    /*package*/ static final SProperty condition$KGVo = MetaAdapterFactory.getProperty(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00730L, 0xac4a12cce5dbb8cL, "condition");
    /*package*/ static final SProperty targetClass$DeM6 = MetaAdapterFactory.getProperty(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0xac4a12cce5dbb29L, 0xac4a12cce5dbb90L, "targetClass");
    /*package*/ static final SProperty targetSignature$Dfg8 = MetaAdapterFactory.getProperty(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0xac4a12cce5dbb29L, 0xac4a12cce5dbb92L, "targetSignature");
    /*package*/ static final SProperty type$CSJA = MetaAdapterFactory.getProperty(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0xac4a12cce5dbb67L, 0xac4a12cce5dbb6bL, "type");
    /*package*/ static final SProperty condition$Dej_ = MetaAdapterFactory.getProperty(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0xac4a12cce5dbb82L, 0xac4a12cce5dbb85L, "condition");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink methods$l8cE = MetaAdapterFactory.getContainmentLink(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00676L, 0x307aac0c73c00739L, "methods");
    /*package*/ static final SReferenceLink entryMethod$61f3 = MetaAdapterFactory.getReferenceLink(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00676L, 0x8951dc60033228fL, "entryMethod");
    /*package*/ static final SContainmentLink blocks$sZ2f = MetaAdapterFactory.getContainmentLink(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00733L, 0x307aac0c73c21c1cL, "blocks");
    /*package*/ static final SReferenceLink targetMethod$n8Sj = MetaAdapterFactory.getReferenceLink(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0xac4a12cce5dbb29L, 0xac4a12cce8d544fL, "targetMethod");
    /*package*/ static final SContainmentLink invocations$KHap = MetaAdapterFactory.getContainmentLink(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00730L, 0xac4a12cce5dbb8dL, "invocations");
    /*package*/ static final SReferenceLink target$ND_8 = MetaAdapterFactory.getReferenceLink(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0xac4a12cce81e454L, 0xac4a12cce82116dL, "target");
    /*package*/ static final SContainmentLink successors$7u8o = MetaAdapterFactory.getContainmentLink(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00730L, 0xac4a12cce8228c1L, "successors");
    /*package*/ static final SReferenceLink entryBlock$4nNX = MetaAdapterFactory.getReferenceLink(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00733L, 0xac4a12cce6735aeL, "entryBlock");
    /*package*/ static final SReferenceLink originBlock$zItN = MetaAdapterFactory.getReferenceLink(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0xac4a12cce5dbb67L, 0x8951dc6006dbbd1L, "originBlock");
    /*package*/ static final SReferenceLink targetMethod$BvBI = MetaAdapterFactory.getReferenceLink(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0xac4a12cce5dbb6fL, 0x8951dc600573183L, "targetMethod");
    /*package*/ static final SContainmentLink interactions$KgkV = MetaAdapterFactory.getContainmentLink(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00733L, 0xac4a12cce5dbb66L, "interactions");
    /*package*/ static final SContainmentLink successors$CY8X = MetaAdapterFactory.getContainmentLink(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0xac4a12cce5dbb67L, 0xac4a12cce5dbb6dL, "successors");
    /*package*/ static final SContainmentLink backwardJumps$DcVr = MetaAdapterFactory.getContainmentLink(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0xac4a12cce5dbb7cL, 0xac4a12cce5dbb80L, "backwardJumps");
    /*package*/ static final SContainmentLink cfg$G$Mq = MetaAdapterFactory.getContainmentLink(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c0072eL, 0x307aac0c73c0be32L, "cfg");
  }
}
