package EnhancedCallGraph.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SConcept;

public final class Loop__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0xac4a12cce5dbb7cL, "EnhancedCallGraph.structure.Loop");

  public static final SMethod<Iterable<SNode>> getNestedInteractions_id1lBv0KRsoSo = new SMethodBuilder<Iterable<SNode>>(new SJavaCompoundTypeImpl((Class<Iterable<SNode>>) ((Class) Object.class))).name("getNestedInteractions").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(1542337789309324824L).languageId(0xa90450ec00d1159aL, 0x8fec4b91acc14b63L).build2();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(getNestedInteractions_id1lBv0KRsoSo);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static Iterable<SNode> getNestedInteractions_id1lBv0KRsoSo(@NotNull SNode __thisNode__) {
    final List<SNode> visited = ListSequence.fromList(new ArrayList<SNode>());
    List<SNode> queue = ListSequence.fromList(new ArrayList<SNode>());

    for (SNode s : ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(__thisNode__, LINKS.originBlock$zItN), LINKS.successors$7u8o))) {
      ListSequence.fromList(queue).addElement(SLinkOperations.getTarget(s, LINKS.target$ND_8));
    }

    while (ListSequence.fromList(queue).isNotEmpty()) {
      final SNode current = ListSequence.fromList(queue).removeElementAt(0);

      if (ListSequence.fromList(visited).contains(current)) {
        continue;
      }
      ListSequence.fromList(visited).addElement(current);


      if (ListSequence.fromList(SLinkOperations.getChildren(__thisNode__, LINKS.backwardJumps$DcVr)).any((it) -> SLinkOperations.getTarget(it, LINKS.target$ND_8) == current)) {
        continue;
      }


      for (SNode succ : ListSequence.fromList(SLinkOperations.getChildren(current, LINKS.successors$7u8o))) {
        ListSequence.fromList(queue).addElement(SLinkOperations.getTarget(succ, LINKS.target$ND_8));
      }
    }

    SNode cfg = SNodeOperations.getNodeAncestor(__thisNode__, CONCEPTS.ControlFlowGraph$lf, false, false);

    return ListSequence.fromList(SLinkOperations.getChildren(cfg, LINKS.interactions$KgkV)).where((it) -> ListSequence.fromList(visited).contains(SLinkOperations.getTarget(it, LINKS.originBlock$zItN)));

  }

  /*package*/ Loop__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((Iterable<SNode>) getNestedInteractions_id1lBv0KRsoSo(node));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink target$ND_8 = MetaAdapterFactory.getReferenceLink(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0xac4a12cce81e454L, 0xac4a12cce82116dL, "target");
    /*package*/ static final SReferenceLink originBlock$zItN = MetaAdapterFactory.getReferenceLink(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0xac4a12cce5dbb67L, 0x8951dc6006dbbd1L, "originBlock");
    /*package*/ static final SContainmentLink successors$7u8o = MetaAdapterFactory.getContainmentLink(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00730L, 0xac4a12cce8228c1L, "successors");
    /*package*/ static final SContainmentLink backwardJumps$DcVr = MetaAdapterFactory.getContainmentLink(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0xac4a12cce5dbb7cL, 0xac4a12cce5dbb80L, "backwardJumps");
    /*package*/ static final SContainmentLink interactions$KgkV = MetaAdapterFactory.getContainmentLink(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00733L, 0xac4a12cce5dbb66L, "interactions");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ControlFlowGraph$lf = MetaAdapterFactory.getConcept(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00733L, "EnhancedCallGraph.structure.ControlFlowGraph");
  }
}
