package ImportGraph.main;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SModel;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.Files;
import com.google.gson.Gson;
import com.google.gson.JsonObject;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.Sequence;
import java.util.Map;
import java.util.HashMap;
import com.google.gson.JsonArray;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class GraphImporter {
  public static void importJSON(SModel model) {
    try {
      String path = "/Users/alessandramancas/projects/appliJava/ecg.json";
      Path p = Paths.get(path);
      String content = new String(Files.readAllBytes(p));

      Gson gson = new Gson();
      JsonObject JSONroot = gson.fromJson(content, JsonObject.class);

      SNode ecg = null;

      for (SNode root : model.getRootNodes()) {
        if (root.getConcept().getName().equals("EnhancedCallGraph")) {
          ecg = root;
          break;
        }
      }

      for (SNode method : Sequence.fromIterable(ecg.getChildren())) {
        ecg.removeChild(method);
      }

      Map<String, SNode> methodMap = new HashMap<>();

      JsonArray methods = JSONroot.getAsJsonArray("methods");

      //  Pass 1 - create methods only
      for (Integer i = 0; i < methods.size(); i++) {
        JsonObject m = methods.get(i).getAsJsonObject();

        String name = m.get("id").getAsString();
        String methodName = m.get("methodName").getAsString();
        String signatureString = m.get("signature").getAsString();
        String returnType = m.get("returnType").getAsString();
        String className = m.get("className").getAsString();
        String isEntry = m.get("isEntry").getAsString();

        SNode methodNode = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c0072eL, "EnhancedCallGraph.structure.Method"));
        setProp(methodNode, "name", name);
        setProp(methodNode, "methodName", methodName);
        setProp(methodNode, "signature", signatureString);
        setProp(methodNode, "returnType", returnType);
        setProp(methodNode, "class", className);
        setProp(methodNode, "isEntry", isEntry);

        addChild(ecg, "methods", methodNode);
        methodMap.put(signatureString, methodNode);

      }

      //  then set the entry method
      String entrySig = JSONroot.get("entryMethod").getAsString();
      SNode entryNode = methodMap.get(entrySig);


    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  private static void setProp(SNode node, String propName, String value) {
    for (SProperty p : node.getProperties()) {
      if (p.getName().equals(propName)) {
        node.setProperty(p, value);
        //  there may be problem for isEntry later?
        return;
      }
    }
  }

  private static void addChild(SNode parent, String roleName, SNode child) {
    for (SContainmentLink l : parent.getConcept().getContainmentLinks()) {
      if (l.getName().equals(roleName)) {
        parent.addChild(l, child);
        return;
      }
    }
  }

  public static SNode testFindECG(SModel model) {
    SNode ecg = null;
    for (SNode root : model.getRootNodes()) {
      System.out.println("Root found: " + root.getConcept().getName());

      if (root.getConcept().getName().equals("EnhancedCallGraph")) {
        ecg = root;
        break;
      }

      if (ecg == null) {
        throw new RuntimeException("No ECG Root found!");
      }
      System.out.println("Found ECG Root!");

      final SNode theECG = ecg;

      return theECG;
    }
    return null;
  }

  public static void testAddMethod(SNode ecg) {
    SNode testMethod = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c0072eL, "EnhancedCallGraph.structure.Method"));
    SPropertyOperations.assign(testMethod, PROPS.name$MnvL, "TEST_METHOD");
    ListSequence.fromList(SLinkOperations.getChildren(ecg, LINKS.methods$l8cE)).addElement(testMethod);
  }

  public static void main(String[] args) {
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink methods$l8cE = MetaAdapterFactory.getContainmentLink(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00676L, 0x307aac0c73c00739L, "methods");
  }
}
