package ImportGraph.main;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class JSONtoECGImporter {
  public static void main(String[] args) {
    SNode g = null;
    SNode block = null;

    String graphConcept = "EnhancedCallGraph.structure.EnhancedCallGraph";
    String blockConcept = "EnhancedCallGraph.structure.Block";


  }
}
