package ImportGraph.main;

/*Generated by MPS */


public class testImport {
  public static void main(String[] args) throws Exception {
    String path = "/Users/alessandramancas/projects/appliJava/ecg.json";



  }
}
