package EnhancedCallGraph.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_Block;
  private ConceptPresentation props_ControlFlowGraph;
  private ConceptPresentation props_EnhancedCallGraph;
  private ConceptPresentation props_Method;
  private ConceptPresentation props_ObjectOccurrence;
  private ConceptPresentation props_Parameter;
  private ConceptPresentation props_Statement;
  private ConceptPresentation props_SuccessorList;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.Block:
        if (props_Block == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Block = cpb.create();
        }
        return props_Block;
      case LanguageConceptSwitch.ControlFlowGraph:
        if (props_ControlFlowGraph == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("ControlFlowGraph");
          props_ControlFlowGraph = cpb.create();
        }
        return props_ControlFlowGraph;
      case LanguageConceptSwitch.EnhancedCallGraph:
        if (props_EnhancedCallGraph == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("EnhancedCallGraph");
          props_EnhancedCallGraph = cpb.create();
        }
        return props_EnhancedCallGraph;
      case LanguageConceptSwitch.Method:
        if (props_Method == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Method = cpb.create();
        }
        return props_Method;
      case LanguageConceptSwitch.ObjectOccurrence:
        if (props_ObjectOccurrence == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("ObjectOccurrence");
          props_ObjectOccurrence = cpb.create();
        }
        return props_ObjectOccurrence;
      case LanguageConceptSwitch.Parameter:
        if (props_Parameter == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Parameter = cpb.create();
        }
        return props_Parameter;
      case LanguageConceptSwitch.Statement:
        if (props_Statement == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Statement");
          props_Statement = cpb.create();
        }
        return props_Statement;
      case LanguageConceptSwitch.SuccessorList:
        if (props_SuccessorList == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("SuccessorList");
          props_SuccessorList = cpb.create();
        }
        return props_SuccessorList;
    }
    return null;
  }
}
