package EnhancedCallGraph.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_Block;
  private ConceptPresentation props_BlockList;
  private ConceptPresentation props_BlockRef;
  private ConceptPresentation props_ControlFlowGraph;
  private ConceptPresentation props_ControlStructure;
  private ConceptPresentation props_EnhancedCallGraph;
  private ConceptPresentation props_IfStatement;
  private ConceptPresentation props_Interaction;
  private ConceptPresentation props_Invocation;
  private ConceptPresentation props_Loop;
  private ConceptPresentation props_Method;
  private ConceptPresentation props_MethodCall;
  private ConceptPresentation props_Parameter;
  private ConceptPresentation props_ParameterList;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.Block:
        if (props_Block == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Block = cpb.create();
        }
        return props_Block;
      case LanguageConceptSwitch.BlockList:
        if (props_BlockList == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("BlockList");
          props_BlockList = cpb.create();
        }
        return props_BlockList;
      case LanguageConceptSwitch.BlockRef:
        if (props_BlockRef == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByReference(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0xac4a12cce81e454L, 0xac4a12cce82116dL, "target", "", "");
          props_BlockRef = cpb.create();
        }
        return props_BlockRef;
      case LanguageConceptSwitch.ControlFlowGraph:
        if (props_ControlFlowGraph == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByReference(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00733L, 0xac4a12cce6735aeL, "entryBlock", "", "");
          props_ControlFlowGraph = cpb.create();
        }
        return props_ControlFlowGraph;
      case LanguageConceptSwitch.ControlStructure:
        if (props_ControlStructure == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_ControlStructure = cpb.create();
        }
        return props_ControlStructure;
      case LanguageConceptSwitch.EnhancedCallGraph:
        if (props_EnhancedCallGraph == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByReference(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00676L, 0x8951dc60033228fL, "entryMethod", "", "");
          props_EnhancedCallGraph = cpb.create();
        }
        return props_EnhancedCallGraph;
      case LanguageConceptSwitch.IfStatement:
        if (props_IfStatement == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("IfStatement");
          props_IfStatement = cpb.create();
        }
        return props_IfStatement;
      case LanguageConceptSwitch.Interaction:
        if (props_Interaction == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_Interaction = cpb.create();
        }
        return props_Interaction;
      case LanguageConceptSwitch.Invocation:
        if (props_Invocation == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByReference(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0xac4a12cce5dbb29L, 0xac4a12cce8d544fL, "targetMethod", "", "");
          props_Invocation = cpb.create();
        }
        return props_Invocation;
      case LanguageConceptSwitch.Loop:
        if (props_Loop == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Loop");
          props_Loop = cpb.create();
        }
        return props_Loop;
      case LanguageConceptSwitch.Method:
        if (props_Method == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Method = cpb.create();
        }
        return props_Method;
      case LanguageConceptSwitch.MethodCall:
        if (props_MethodCall == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("MethodCall");
          props_MethodCall = cpb.create();
        }
        return props_MethodCall;
      case LanguageConceptSwitch.Parameter:
        if (props_Parameter == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Parameter = cpb.create();
        }
        return props_Parameter;
      case LanguageConceptSwitch.ParameterList:
        if (props_ParameterList == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("ParameterList");
          props_ParameterList = cpb.create();
        }
        return props_ParameterList;
    }
    return null;
  }
}
