package EnhancedCallGraph.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Block = 0;
  public static final int ControlFlowGraph = 1;
  public static final int EnhancedCallGraph = 2;
  public static final int Method = 3;
  public static final int ObjectOccurrence = 4;
  public static final int Parameter = 5;
  public static final int Statement = 6;
  public static final int SuccessorList = 7;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL);
    builder.put(0x307aac0c73c00730L, Block);
    builder.put(0x307aac0c73c00733L, ControlFlowGraph);
    builder.put(0x307aac0c73c00676L, EnhancedCallGraph);
    builder.put(0x307aac0c73c0072eL, Method);
    builder.put(0x307aac0c73c04435L, ObjectOccurrence);
    builder.put(0x307aac0c73c0442cL, Parameter);
    builder.put(0x307aac0c73c00736L, Statement);
    builder.put(0x307aac0c73c0bca0L, SuccessorList);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
