package EnhancedCallGraph.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptBlock = createDescriptorForBlock();
  /*package*/ final ConceptDescriptor myConceptControlFlowGraph = createDescriptorForControlFlowGraph();
  /*package*/ final ConceptDescriptor myConceptEnhancedCallGraph = createDescriptorForEnhancedCallGraph();
  /*package*/ final ConceptDescriptor myConceptMethod = createDescriptorForMethod();
  /*package*/ final ConceptDescriptor myConceptObjectOccurrence = createDescriptorForObjectOccurrence();
  /*package*/ final ConceptDescriptor myConceptParameter = createDescriptorForParameter();
  /*package*/ final ConceptDescriptor myConceptStatement = createDescriptorForStatement();
  /*package*/ final ConceptDescriptor myConceptSuccessorList = createDescriptorForSuccessorList();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptBlock, myConceptControlFlowGraph, myConceptEnhancedCallGraph, myConceptMethod, myConceptObjectOccurrence, myConceptParameter, myConceptStatement, myConceptSuccessorList);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Block:
        return myConceptBlock;
      case LanguageConceptSwitch.ControlFlowGraph:
        return myConceptControlFlowGraph;
      case LanguageConceptSwitch.EnhancedCallGraph:
        return myConceptEnhancedCallGraph;
      case LanguageConceptSwitch.Method:
        return myConceptMethod;
      case LanguageConceptSwitch.ObjectOccurrence:
        return myConceptObjectOccurrence;
      case LanguageConceptSwitch.Parameter:
        return myConceptParameter;
      case LanguageConceptSwitch.Statement:
        return myConceptStatement;
      case LanguageConceptSwitch.SuccessorList:
        return myConceptSuccessorList;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForBlock() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("EnhancedCallGraph", "Block", 0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00730L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c796c4a3-2b8c-48ab-8dfa-f48c064ae694(EnhancedCallGraph.structure)/3493293630460790576");
    b.version(3);
    b.aggregate("successors", 0x307aac0c73c0bca3L).target(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c0bca0L).optional(true).ordered(true).multiple(false).origin("3493293630460837027").done();
    b.aggregate("statements", 0x307aac0c73c0bca6L).target(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00736L).optional(true).ordered(true).multiple(true).origin("3493293630460837030").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForControlFlowGraph() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("EnhancedCallGraph", "ControlFlowGraph", 0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00733L);
    b.class_(false, false, false);
    b.origin("r:c796c4a3-2b8c-48ab-8dfa-f48c064ae694(EnhancedCallGraph.structure)/3493293630460790579");
    b.version(3);
    b.aggregate("blocks", 0x307aac0c73c00734L).target(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00730L).optional(true).ordered(true).multiple(true).origin("3493293630460790580").done();
    b.aggregate("entryBlock", 0x307aac0c73c0bc9eL).target(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00730L).optional(true).ordered(true).multiple(false).origin("3493293630460837022").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEnhancedCallGraph() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("EnhancedCallGraph", "EnhancedCallGraph", 0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00676L);
    b.class_(false, false, true);
    b.origin("r:c796c4a3-2b8c-48ab-8dfa-f48c064ae694(EnhancedCallGraph.structure)/3493293630460790390");
    b.version(3);
    b.property("entryMethod", 0x307aac0c73c0bd66L).type(PrimitiveTypeId.STRING).origin("3493293630460837222").done();
    b.aggregate("methods", 0x307aac0c73c00739L).target(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c0072eL).optional(true).ordered(true).multiple(true).origin("3493293630460790585").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMethod() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("EnhancedCallGraph", "Method", 0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c0072eL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c796c4a3-2b8c-48ab-8dfa-f48c064ae694(EnhancedCallGraph.structure)/3493293630460790574");
    b.version(3);
    b.property("isEntry", 0x307aac0c73c04427L).type(PrimitiveTypeId.BOOLEAN).origin("3493293630460806183").done();
    b.property("id", 0x307aac0c73c04428L).type(PrimitiveTypeId.STRING).origin("3493293630460806184").done();
    b.property("signature", 0x307aac0c73c04429L).type(PrimitiveTypeId.STRING).origin("3493293630460806185").done();
    b.property("returnType", 0x307aac0c73c04431L).type(PrimitiveTypeId.STRING).origin("3493293630460806193").done();
    b.property("className", 0x307aac0c73c04436L).type(PrimitiveTypeId.STRING).origin("3493293630460806198").done();
    b.aggregate("params", 0x307aac0c73c0442fL).target(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c0442cL).optional(true).ordered(true).multiple(true).origin("3493293630460806191").done();
    b.aggregate("cfg", 0x307aac0c73c0be32L).target(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00733L).optional(true).ordered(true).multiple(false).origin("3493293630460837426").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForObjectOccurrence() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("EnhancedCallGraph", "ObjectOccurrence", 0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c04435L);
    b.class_(false, false, false);
    b.origin("r:c796c4a3-2b8c-48ab-8dfa-f48c064ae694(EnhancedCallGraph.structure)/3493293630460806197");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForParameter() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("EnhancedCallGraph", "Parameter", 0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c0442cL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c796c4a3-2b8c-48ab-8dfa-f48c064ae694(EnhancedCallGraph.structure)/3493293630460806188");
    b.version(3);
    b.property("type", 0x307aac0c73c0442eL).type(PrimitiveTypeId.STRING).origin("3493293630460806190").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStatement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("EnhancedCallGraph", "Statement", 0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00736L);
    b.class_(false, false, false);
    b.origin("r:c796c4a3-2b8c-48ab-8dfa-f48c064ae694(EnhancedCallGraph.structure)/3493293630460790582");
    b.version(3);
    b.property("contents", 0x307aac0c73c0bca8L).type(PrimitiveTypeId.STRING).origin("3493293630460837032").done();
    b.property("isReturn", 0x307aac0c73c0bca9L).type(PrimitiveTypeId.BOOLEAN).origin("3493293630460837033").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSuccessorList() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("EnhancedCallGraph", "SuccessorList", 0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c0bca0L);
    b.class_(false, false, false);
    b.origin("r:c796c4a3-2b8c-48ab-8dfa-f48c064ae694(EnhancedCallGraph.structure)/3493293630460837024");
    b.version(3);
    b.aggregate("blocks", 0x307aac0c73c0bca1L).target(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00730L).optional(true).ordered(true).multiple(true).origin("3493293630460837025").done();
    return b.create();
  }
}
