package PlantUMLTarget.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class AltFragment_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("alt");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.condition$IfAZ));
    tgs.append("\n");
    for (SNode item : SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.thenLines$Il0m)) {
      tgs.appendNode(item);
    }
    tgs.append("\n");
    tgs.append("else\n");
    for (SNode item : SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.elseLines$_aAd)) {
      tgs.appendNode(item);
    }
    tgs.append("\n");
    tgs.append("end");
  }

  private static final class PROPS {
    /*package*/ static final SProperty condition$IfAZ = MetaAdapterFactory.getProperty(0x3946306a58ce49edL, 0x90e5f6877939cd31L, 0x3cf5cbefbb5c29e1L, 0x3cf5cbefbb5c29e3L, "condition");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink thenLines$Il0m = MetaAdapterFactory.getContainmentLink(0x3946306a58ce49edL, 0x90e5f6877939cd31L, 0x3cf5cbefbb5c29e1L, 0x3cf5cbefbb5c29e5L, "thenLines");
    /*package*/ static final SContainmentLink elseLines$_aAd = MetaAdapterFactory.getContainmentLink(0x3946306a58ce49edL, 0x90e5f6877939cd31L, 0x3cf5cbefbb5c29e1L, 0x15677c0c376f6f96L, "elseLines");
  }
}
