package PlantUMLTarget.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class LoopFragment_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append(" loop ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.condition$VscZ));
    tgs.append(" \n ");

    for (SNode item : SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.lines$VxAm)) {
      tgs.appendNode(item);
    }

    tgs.append(" end ");
    tgs.append("\n");
  }

  private static final class PROPS {
    /*package*/ static final SProperty condition$VscZ = MetaAdapterFactory.getProperty(0x3946306a58ce49edL, 0x90e5f6877939cd31L, 0x543e8aec4e3d4879L, 0x543e8aec4e3d487bL, "condition");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink lines$VxAm = MetaAdapterFactory.getContainmentLink(0x3946306a58ce49edL, 0x90e5f6877939cd31L, 0x543e8aec4e3d4879L, 0x543e8aec4e3d487dL, "lines");
  }
}
