package PlantUMLTarget.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class MessageLine_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.from$ZfFZ));
    tgs.append(" -> ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.to$Zgp2));
    tgs.append(" : ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.label$ZgC3));
    tgs.append("\n");
  }

  private static final class PROPS {
    /*package*/ static final SProperty from$ZfFZ = MetaAdapterFactory.getProperty(0x3946306a58ce49edL, 0x90e5f6877939cd31L, 0x543e8aec4e2006c5L, 0x543e8aec4e2006c7L, "from");
    /*package*/ static final SProperty to$Zgp2 = MetaAdapterFactory.getProperty(0x3946306a58ce49edL, 0x90e5f6877939cd31L, 0x543e8aec4e2006c5L, 0x543e8aec4e2006caL, "to");
    /*package*/ static final SProperty label$ZgC3 = MetaAdapterFactory.getProperty(0x3946306a58ce49edL, 0x90e5f6877939cd31L, 0x543e8aec4e2006c5L, 0x543e8aec4e2006cbL, "label");
  }
}
