package PlantUMLTarget.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class PUMLFile_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("@startuml\n");
    for (SNode item : SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.lines$Zeio)) {
      tgs.appendNode(item);
    }
    tgs.append("\n@enduml");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink lines$Zeio = MetaAdapterFactory.getContainmentLink(0x3946306a58ce49edL, 0x90e5f6877939cd31L, 0x543e8aec4e2006bcL, 0x543e8aec4e2006c2L, "lines");
  }
}
