package PlantUMLTarget.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenAspectBase;
import PlantUMLTarget.structure.LanguageConceptSwitch;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.text.rt.TextGenDescriptor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.text.rt.TextGenModelOutline;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class TextGenAspectDescriptor extends TextGenAspectBase {
  private final LanguageConceptSwitch myIndex = new LanguageConceptSwitch();

  public TextGenAspectDescriptor() {
  }

  @Nullable
  @Override
  public TextGenDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    switch (myIndex.index(concept)) {
      case LanguageConceptSwitch.AltFragment:
        return new AltFragment_TextGen();
      case LanguageConceptSwitch.LoopFragment:
        return new LoopFragment_TextGen();
      case LanguageConceptSwitch.MessageLine:
        return new MessageLine_TextGen();
      case LanguageConceptSwitch.PUMLFile:
        return new PUMLFile_TextGen();
    }
    return null;
  }

  @Override
  public void breakdownToUnits(@NotNull TextGenModelOutline outline) {
    for (SNode root : outline.getModel().getRootNodes()) {
      if (root.getConcept().equals(CONCEPTS.PUMLFile$ml)) {
        String fname = getFileName_PUMLFile(root);
        String ext = getFileExtension_PUMLFile(root);
        outline.registerTextUnit((ext == null ? fname : (fname + '.' + ext)), root);
        continue;
      }
    }
  }
  private static String getFileName_PUMLFile(SNode node) {
    return "sequence";
  }
  private static String getFileExtension_PUMLFile(SNode node) {
    return "puml";
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept PUMLFile$ml = MetaAdapterFactory.getConcept(0x3946306a58ce49edL, 0x90e5f6877939cd31L, 0x543e8aec4e2006bcL, "PlantUMLTarget.structure.PUMLFile");
  }
}
