package EnhancedCallGraph.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SConcept;

public class check_EnhancedCallGraph_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public check_EnhancedCallGraph_NonTypesystemRule() {
  }
  public void applyRule(final SNode ecg, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    //  if there is an entryMethod, make sure it's isEntry as well 
    if (SLinkOperations.getTarget(ecg, LINKS.entryMethod$61f3) != null) {
      if (!(SPropertyOperations.getBoolean(SLinkOperations.getTarget(ecg, LINKS.entryMethod$61f3), PROPS.isEntry$8MEG))) {
        {
          final MessageTarget errorTarget = new NodeMessageTarget();
          IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(SLinkOperations.getTarget(ecg, LINKS.entryMethod$61f3), "Entry method must be isEntry", "r:98ab8d49-e3e8-4572-9bee-cdf8a8c1fa86(EnhancedCallGraph.typesystem)", "3689884152909926410", null, errorTarget);
        }
      }
    } else {
      {
        final MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(ecg, "Must have an entryMethod", "r:98ab8d49-e3e8-4572-9bee-cdf8a8c1fa86(EnhancedCallGraph.typesystem)", "3689884152909928778", null, errorTarget);
      }
    }

    int count = 0;
    for (SNode m : ListSequence.fromList(SLinkOperations.getChildren(ecg, LINKS.methods$l8cE))) {
      if (SPropertyOperations.getBoolean(m, PROPS.isEntry$8MEG)) {
        count = count + 1;
      }
    }
    if (count > 1) {
      for (SNode m : ListSequence.fromList(SLinkOperations.getChildren(ecg, LINKS.methods$l8cE))) {
        if (SPropertyOperations.getBoolean(m, PROPS.isEntry$8MEG)) {
          {
            final MessageTarget errorTarget = new NodeMessageTarget();
            IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(m, "Only one method may have isEntry=true", "r:98ab8d49-e3e8-4572-9bee-cdf8a8c1fa86(EnhancedCallGraph.typesystem)", "1863019716066539088", null, errorTarget);
          }
        }
      }
    }

  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.EnhancedCallGraph$bW;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink entryMethod$61f3 = MetaAdapterFactory.getReferenceLink(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00676L, 0x8951dc60033228fL, "entryMethod");
    /*package*/ static final SContainmentLink methods$l8cE = MetaAdapterFactory.getContainmentLink(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00676L, 0x307aac0c73c00739L, "methods");
  }

  private static final class PROPS {
    /*package*/ static final SProperty isEntry$8MEG = MetaAdapterFactory.getProperty(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c0072eL, 0x307aac0c73c04427L, "isEntry");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept EnhancedCallGraph$bW = MetaAdapterFactory.getConcept(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00676L, "EnhancedCallGraph.structure.EnhancedCallGraph");
  }
}
