package EnhancedCallGraph.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class check_Loop_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public check_Loop_NonTypesystemRule() {
  }
  public void applyRule(final SNode loop, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    //  BackwardJumps must refer to blocks in the cfg
    SNode cfg = SNodeOperations.getNodeAncestor(loop, CONCEPTS.ControlFlowGraph$lf, false, false);
    for (SNode blockRef : ListSequence.fromList(SLinkOperations.getChildren(loop, LINKS.backwardJumps$DcVr))) {
      if (!(SLinkOperations.getChildren(cfg, LINKS.blocks$sZ2f).contains(SLinkOperations.getTarget(blockRef, LINKS.target$ND_8)))) {
        {
          final MessageTarget errorTarget = new NodeMessageTarget();
          IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(loop, "BackwardJumps must refer to CFG blocks", "r:98ab8d49-e3e8-4572-9bee-cdf8a8c1fa86(EnhancedCallGraph.typesystem)", "618433260085748317", null, errorTarget);
        }
      }
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.Loop$3m;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ControlFlowGraph$lf = MetaAdapterFactory.getConcept(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00733L, "EnhancedCallGraph.structure.ControlFlowGraph");
    /*package*/ static final SConcept Loop$3m = MetaAdapterFactory.getConcept(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0xac4a12cce5dbb7cL, "EnhancedCallGraph.structure.Loop");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink blocks$sZ2f = MetaAdapterFactory.getContainmentLink(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00733L, 0x307aac0c73c21c1cL, "blocks");
    /*package*/ static final SReferenceLink target$ND_8 = MetaAdapterFactory.getReferenceLink(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0xac4a12cce81e454L, 0xac4a12cce82116dL, "target");
    /*package*/ static final SContainmentLink backwardJumps$DcVr = MetaAdapterFactory.getContainmentLink(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0xac4a12cce5dbb7cL, 0xac4a12cce5dbb80L, "backwardJumps");
  }
}
