package EnhancedCallGraph.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class ControlStructure_Constraints extends BaseConstraintsDescriptor {
  /*package*/ ControlStructure_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.ControlStructure$gr, initContext);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ControlStructure$gr = MetaAdapterFactory.getConcept(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0xac4a12cce5dbb82L, "EnhancedCallGraph.structure.ControlStructure");
  }
}
