package EnhancedCallGraph.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseScopeProvider;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import jetbrains.mps.scope.ListScope;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class EnhancedCallGraph_Constraints extends BaseConstraintsDescriptor {
  /*package*/ EnhancedCallGraph_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.EnhancedCallGraph$bW, initContext);
    record(new RD1(this));
  }

  /*package*/ static final class RD1 extends BaseReferenceConstraintsDescriptor {
    /*package*/ RD1(ConstraintsDescriptor container) {
      super(LINKS.entryMethod$61f3, container, true, false);
    }
    @Nullable
    @Override
    public ReferenceScopeProvider getScopeProvider() {
      return new BaseScopeProvider() {
        @Override
        public SNodeReference getSearchScopeValidatorNode() {
          return new SNodePointer("r:e42ad3ae-bd1c-434b-a4bc-0e7cbd077edb(EnhancedCallGraph.constraints)", "618433260079142569");
        }
        @Override
        public Scope createScope(final ReferenceConstraintsContext _context) {
          return ListScope.forNamedElements(SLinkOperations.getChildren(_context.getReferenceNode(), LINKS.methods$l8cE));
        }
      };
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept EnhancedCallGraph$bW = MetaAdapterFactory.getConcept(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00676L, "EnhancedCallGraph.structure.EnhancedCallGraph");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink entryMethod$61f3 = MetaAdapterFactory.getReferenceLink(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00676L, 0x8951dc60033228fL, "entryMethod");
    /*package*/ static final SContainmentLink methods$l8cE = MetaAdapterFactory.getContainmentLink(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c00676L, 0x307aac0c73c00739L, "methods");
  }
}
