package EnhancedCallGraph.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Method_Constraints extends BaseConstraintsDescriptor {
  /*package*/ Method_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.Method$iO, initContext);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Method$iO = MetaAdapterFactory.getConcept(0x8fec4b91acc14b63L, 0xa90450ec00d1159aL, 0x307aac0c73c0072eL, "EnhancedCallGraph.structure.Method");
  }
}
