package PlantUMLTarget.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_AltFragment;
  private ConceptPresentation props_LoopFragment;
  private ConceptPresentation props_MessageLine;
  private ConceptPresentation props_PUMLFile;
  private ConceptPresentation props_SequenceElement;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.AltFragment:
        if (props_AltFragment == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("AltFragment");
          props_AltFragment = cpb.create();
        }
        return props_AltFragment;
      case LanguageConceptSwitch.LoopFragment:
        if (props_LoopFragment == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("LoopFragment");
          props_LoopFragment = cpb.create();
        }
        return props_LoopFragment;
      case LanguageConceptSwitch.MessageLine:
        if (props_MessageLine == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("MessageLine");
          props_MessageLine = cpb.create();
        }
        return props_MessageLine;
      case LanguageConceptSwitch.PUMLFile:
        if (props_PUMLFile == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("PUMLFile");
          props_PUMLFile = cpb.create();
        }
        return props_PUMLFile;
      case LanguageConceptSwitch.SequenceElement:
        if (props_SequenceElement == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_SequenceElement = cpb.create();
        }
        return props_SequenceElement;
    }
    return null;
  }
}
