package PlantUMLTarget.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AltFragment = 0;
  public static final int LoopFragment = 1;
  public static final int MessageLine = 2;
  public static final int PUMLFile = 3;
  public static final int SequenceElement = 4;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x3946306a58ce49edL, 0x90e5f6877939cd31L);
    builder.put(0x3cf5cbefbb5c29e1L, AltFragment);
    builder.put(0x543e8aec4e3d4879L, LoopFragment);
    builder.put(0x543e8aec4e2006c5L, MessageLine);
    builder.put(0x543e8aec4e2006bcL, PUMLFile);
    builder.put(0x543e8aec4e411056L, SequenceElement);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
