package PlantUMLTarget.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAltFragment = createDescriptorForAltFragment();
  /*package*/ final ConceptDescriptor myConceptLoopFragment = createDescriptorForLoopFragment();
  /*package*/ final ConceptDescriptor myConceptMessageLine = createDescriptorForMessageLine();
  /*package*/ final ConceptDescriptor myConceptPUMLFile = createDescriptorForPUMLFile();
  /*package*/ final ConceptDescriptor myConceptSequenceElement = createDescriptorForSequenceElement();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAltFragment, myConceptLoopFragment, myConceptMessageLine, myConceptPUMLFile, myConceptSequenceElement);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.AltFragment:
        return myConceptAltFragment;
      case LanguageConceptSwitch.LoopFragment:
        return myConceptLoopFragment;
      case LanguageConceptSwitch.MessageLine:
        return myConceptMessageLine;
      case LanguageConceptSwitch.PUMLFile:
        return myConceptPUMLFile;
      case LanguageConceptSwitch.SequenceElement:
        return myConceptSequenceElement;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAltFragment() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PlantUMLTarget", "AltFragment", 0x3946306a58ce49edL, 0x90e5f6877939cd31L, 0x3cf5cbefbb5c29e1L);
    b.class_(false, false, false);
    // extends: PlantUMLTarget.structure.SequenceElement
    b.super_(0x3946306a58ce49edL, 0x90e5f6877939cd31L, 0x543e8aec4e411056L);
    b.origin("r:4ec236bb-6f9c-4269-838e-b3e7e6585431(PlantUMLTarget.structure)/4392641242070788577");
    b.version(3);
    b.property("condition", 0x3cf5cbefbb5c29e3L).type(PrimitiveTypeId.STRING).origin("4392641242070788579").done();
    b.aggregate("thenLines", 0x3cf5cbefbb5c29e5L).target(0x3946306a58ce49edL, 0x90e5f6877939cd31L, 0x543e8aec4e411056L).optional(true).ordered(true).multiple(true).origin("4392641242070788581").done();
    b.aggregate("elseLines", 0x15677c0c376f6f96L).target(0x3946306a58ce49edL, 0x90e5f6877939cd31L, 0x543e8aec4e411056L).optional(true).ordered(true).multiple(true).origin("1542337789309185942").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLoopFragment() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PlantUMLTarget", "LoopFragment", 0x3946306a58ce49edL, 0x90e5f6877939cd31L, 0x543e8aec4e3d4879L);
    b.class_(false, false, false);
    // extends: PlantUMLTarget.structure.SequenceElement
    b.super_(0x3946306a58ce49edL, 0x90e5f6877939cd31L, 0x543e8aec4e411056L);
    b.origin("r:4ec236bb-6f9c-4269-838e-b3e7e6585431(PlantUMLTarget.structure)/6070442095271561337");
    b.version(3);
    b.property("condition", 0x543e8aec4e3d487bL).type(PrimitiveTypeId.STRING).origin("6070442095271561339").done();
    b.aggregate("lines", 0x543e8aec4e3d487dL).target(0x3946306a58ce49edL, 0x90e5f6877939cd31L, 0x543e8aec4e411056L).optional(true).ordered(true).multiple(true).origin("6070442095271561341").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMessageLine() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PlantUMLTarget", "MessageLine", 0x3946306a58ce49edL, 0x90e5f6877939cd31L, 0x543e8aec4e2006c5L);
    b.class_(false, false, false);
    // extends: PlantUMLTarget.structure.SequenceElement
    b.super_(0x3946306a58ce49edL, 0x90e5f6877939cd31L, 0x543e8aec4e411056L);
    b.origin("r:4ec236bb-6f9c-4269-838e-b3e7e6585431(PlantUMLTarget.structure)/6070442095269643973");
    b.version(3);
    b.property("from", 0x543e8aec4e2006c7L).type(PrimitiveTypeId.STRING).origin("6070442095269643975").done();
    b.property("to", 0x543e8aec4e2006caL).type(PrimitiveTypeId.STRING).origin("6070442095269643978").done();
    b.property("label", 0x543e8aec4e2006cbL).type(PrimitiveTypeId.STRING).origin("6070442095269643979").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPUMLFile() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PlantUMLTarget", "PUMLFile", 0x3946306a58ce49edL, 0x90e5f6877939cd31L, 0x543e8aec4e2006bcL);
    b.class_(false, false, true);
    b.origin("r:4ec236bb-6f9c-4269-838e-b3e7e6585431(PlantUMLTarget.structure)/6070442095269643964");
    b.version(3);
    b.aggregate("lines", 0x543e8aec4e2006c2L).target(0x3946306a58ce49edL, 0x90e5f6877939cd31L, 0x543e8aec4e411056L).optional(true).ordered(true).multiple(true).origin("6070442095269643970").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSequenceElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PlantUMLTarget", "SequenceElement", 0x3946306a58ce49edL, 0x90e5f6877939cd31L, 0x543e8aec4e411056L);
    b.class_(false, true, false);
    b.origin("r:4ec236bb-6f9c-4269-838e-b3e7e6585431(PlantUMLTarget.structure)/6070442095271809110");
    b.version(3);
    return b.create();
  }
}
